Adding support for PLIC priority threshold register
RapidSilicon/renode-infrastructure_rs pull request #2
Opened 2023-09-14 21:50 UTC by rohanjainRS

### **Summary**
- Adding support to be able to read/write to priority threshold register such that a certain interrupt will only be executed if a source's priority >= a context's priority threshold.
- Changes made to src/Infrastructure/src/Emulator/Cores/RiscV/PLIC/PlatformLevelInterruptControllerBase.cs include function AddContextPriorityThresholdRegisterPLIC() to create priority threshold registers and support read/write abilities. 
- Changes made to src/Infrastructure/src/Emulator/Cores/RiscV/PLIC/IrqContext.cs include creating variable for priority threshold, getter/setter function, and functionality for comparing source's priority to context's priority threshold in AcknowledgePendingInterrupt(). In default constructor, set this.priorityThreshold to 0 (ie capture interrupts of all priorities).
- Changes made to src/Infrastructure/src/Emulator/Cores/RiscV/PlatformLevelInterruptController.cs include creation of priority threshold registers for each context by calling AddContextPriorityThresholdRegisterPLIC() for each context. Also changed addresses of some registers to match those in Gemini code.

### **Testing**
- Tested with a sample program using UART interrupt from ATCUART100 peripheral: 
- The priority threshold of the context and priority of the UART interrupt were testing by changing variables in gemini_interrupt.c. 
- Set PLIC_REGS->properties_context[0].priority_threshold in subsystem_enable_interrupts() to set priority register for context 0. 
- Set PLIC_REGS->priority[irq_source - 18] in irq_map_unmask_and_enable_in_controller() to set priority of UART source.

-  UART will print an ISR message if interrupt is taken, along with corresponding log messages:

![image](https://github.com/RapidSilicon/renode-infrastructure_rs/assets/133986296/f17aa8ac-a9f0-4917-adf0-17f421b39718)

- If UART interrupt is not taken, test program will continue as usual and corresponding log messages will give details:

![image](https://github.com/RapidSilicon/renode-infrastructure_rs/assets/133986296/41a6fd8c-8f3c-4441-b2fd-a41abad08114)

2023-09-15 04:08 UTC, rahul-r-shah requested changes
Some comments to be removed

2023-09-15 04:08 UTC, rahul-r-shah commented on src/Emulator/Cores/RiscV/PLIC/PlatformLevelInterruptControllerBase.cs
> +            //Console.WriteLine("Debugging, PLICbase.cs: WriteDoubleWord(): offset = 0x{0:x8}, value = 0x{1:x8}", offset, value); //debugging
Remove the commented log

2023-09-15 04:08 UTC, rahul-r-shah commented on src/Emulator/Cores/RiscV/PLIC/PlatformLevelInterruptControllerBase.cs
> +            //Console.WriteLine("Debugging, AddContextClaimCompleteRegister(): offset = 0x{0:x8}, contextID = {1}", offset, contextId); //debugging
Remove the commented log

2023-09-15 04:08 UTC, rahul-r-shah commented on src/Emulator/Cores/RiscV/PLIC/PlatformLevelInterruptControllerBase.cs
> +            //Console.WriteLine("Debugging, AddContextEnablesRegister(): maximumSourceDoubleWords = 0x{0:x8}, address = 0x{1:x8}, contextID = {2}", maximumSourceDoubleWords, address, contextId); //de
Remove the commented log

2023-09-15 04:08 UTC, rahul-r-shah commented on src/Emulator/Cores/RiscV/PLIC/PlatformLevelInterruptControllerBase.cs
> +            //Console.WriteLine("Debugging, AddContextPriorityThresholdRegister(): offset = 0x{0:x8}, contextID = {1}", offset, contextId); //debugging
Remove the commented log

2023-09-19 04:09 UTC, jorge-rs requested changes
From my side, changes look good to enable a better PLIC behavior in the model. Please, remove remaining debug messages which are as currently comments

2023-09-19 04:09 UTC, jorge-rs commented on src/Emulator/Cores/RiscV/PLIC/PlatformLevelInterruptControllerBase.cs
> +            //Console.WriteLine("Debugging, PLICbase.cs: ReadDoubleWord(): offset = 0x{0:x8}", offset); //debugging
Delete this one too

2023-09-19 04:48 UTC, jorge-rs approved these changes

2023-09-19 04:49 UTC, jorge-rs approved these changes
LGTM

2023-09-26 04:58 UTC, merged